# Generated by Django 2.1.1 on 2018-09-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmode',
            name='Products',
        ),
        migrations.AddField(
            model_name='cartmode',
            name='Products',
            field=models.ManyToManyField(blank=True, null=True, to='Products.ProductsMode'),
        ),
    ]
