# Generated by Django 2.1.1 on 2018-09-26 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_auto_20180925_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmode',
            name='Products',
        ),
        migrations.AddField(
            model_name='cartmode',
            name='Products',
            field=models.CharField(default='Eekan asa', max_length=130),
        ),
        migrations.AlterField(
            model_name='cartmode',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
