# Generated by Django 2.1.1 on 2018-09-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_auto_20180926_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmode',
            name='user',
            field=models.CharField(default='blessing', max_length=130),
        ),
    ]
