# Generated by Django 2.1.1 on 2018-09-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_auto_20180926_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmode',
            name='Products',
            field=models.CharField(default='', max_length=130),
        ),
        migrations.AlterField(
            model_name='cartmode',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=20),
        ),
    ]
