# Generated by Django 2.1.1 on 2018-09-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_auto_20180926_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmode',
            name='Products',
            field=models.CharField(default='Fruits', max_length=130),
        ),
    ]
