# Generated by Django 2.1.1 on 2018-09-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_auto_20180926_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmode',
            name='Products',
            field=models.CharField(default='Drinks', max_length=130),
        ),
        migrations.AlterField(
            model_name='cartmode',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=50.19, max_digits=20),
        ),
    ]
