# Generated by Django 2.1.1 on 2018-09-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_auto_20180926_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmode',
            name='Products',
            field=models.CharField(default='Fruits', max_length=130),
        ),
        migrations.AlterField(
            model_name='cartmode',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=40.99, max_digits=20),
        ),
    ]
