# Generated by Django 2.1.1 on 2018-09-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_auto_20180929_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmode',
            name='Products',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='cartmode',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cartmode',
            name='user',
            field=models.CharField(max_length=130),
        ),
    ]
