# Generated by Django 2.1.1 on 2018-09-29 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmode',
            name='active_me',
        ),
        migrations.RemoveField(
            model_name='productsmode',
            name='featured',
        ),
    ]
